// Generated by Dagger (https://google.github.io/dagger).
package au.com.carsales.basemodule.viewdata.projectretail.action.showlisting;

import au.com.carsales.basemodule.tracking.model.TrackingViewDataMapper;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class ShowListingActionVDMapper_Factory implements Factory<ShowListingActionVDMapper> {
  private final Provider<TrackingViewDataMapper> trackingViewDataMapperProvider;

  public ShowListingActionVDMapper_Factory(
      Provider<TrackingViewDataMapper> trackingViewDataMapperProvider) {
    this.trackingViewDataMapperProvider = trackingViewDataMapperProvider;
  }

  @Override
  public ShowListingActionVDMapper get() {
    return provideInstance(trackingViewDataMapperProvider);
  }

  public static ShowListingActionVDMapper provideInstance(
      Provider<TrackingViewDataMapper> trackingViewDataMapperProvider) {
    return new ShowListingActionVDMapper(trackingViewDataMapperProvider.get());
  }

  public static ShowListingActionVDMapper_Factory create(
      Provider<TrackingViewDataMapper> trackingViewDataMapperProvider) {
    return new ShowListingActionVDMapper_Factory(trackingViewDataMapperProvider);
  }

  public static ShowListingActionVDMapper newShowListingActionVDMapper(
      TrackingViewDataMapper trackingViewDataMapper) {
    return new ShowListingActionVDMapper(trackingViewDataMapper);
  }
}
