// Generated by Dagger (https://google.github.io/dagger).
package au.com.carsales.basemodule.viewdata.projectretail.action.showitemdetails;

import au.com.carsales.basemodule.tracking.model.TrackingViewDataMapper;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class ShowItemDetailsActionVDMapper_Factory
    implements Factory<ShowItemDetailsActionVDMapper> {
  private final Provider<TrackingViewDataMapper> trackingViewDataMapperProvider;

  public ShowItemDetailsActionVDMapper_Factory(
      Provider<TrackingViewDataMapper> trackingViewDataMapperProvider) {
    this.trackingViewDataMapperProvider = trackingViewDataMapperProvider;
  }

  @Override
  public ShowItemDetailsActionVDMapper get() {
    return provideInstance(trackingViewDataMapperProvider);
  }

  public static ShowItemDetailsActionVDMapper provideInstance(
      Provider<TrackingViewDataMapper> trackingViewDataMapperProvider) {
    return new ShowItemDetailsActionVDMapper(trackingViewDataMapperProvider.get());
  }

  public static ShowItemDetailsActionVDMapper_Factory create(
      Provider<TrackingViewDataMapper> trackingViewDataMapperProvider) {
    return new ShowItemDetailsActionVDMapper_Factory(trackingViewDataMapperProvider);
  }

  public static ShowItemDetailsActionVDMapper newShowItemDetailsActionVDMapper(
      TrackingViewDataMapper trackingViewDataMapper) {
    return new ShowItemDetailsActionVDMapper(trackingViewDataMapper);
  }
}
